# Generated by Django 5.1.3 on 2024-11-25 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(default='default.jpg', upload_to='gallery')),
                ('image2', models.ImageField(default='default.jpg', upload_to='gallery')),
                ('image3', models.ImageField(default='default.jpg', upload_to='gallery')),
                ('image4', models.ImageField(default='default.jpg', upload_to='gallery')),
                ('image5', models.ImageField(default='default.jpg', upload_to='gallery')),
                ('image6', models.ImageField(default='default.jpg', upload_to='gallery')),
                ('image7', models.ImageField(default='default.jpg', upload_to='gallery')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('desc', models.TextField()),
                ('client', models.CharField(max_length=100)),
                ('project_date', models.DateTimeField(auto_now_add=True)),
                ('url', models.CharField(max_length=100)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.agents')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='root.category')),
            ],
        ),
    ]
